name: Build & Release

on:
  push:
    branches: [master]
  tags:
    - "v*"
  pull_request:
    branches: [master]

jobs:
  build-android:
    name: Build Android APK
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.2"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Release
        uses: softprops/action-gh-release@v3
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
